name: NN_DT
 
channels:
    - defaults
    - nvidia
    - conda-forge
 
dependencies:
    - pip=21.1.3
    - python=3.7.10
    - nvidia::cuda-nvcc=11.4
    - conda-forge::cudatoolkit=11.4
    - conda-forge::cudnn=8.1
 
    - pip:
        - tensorflow-gpu==2.8.0
        - numpy
        - scipy
        - matplotlib
